---
title: "**Defining protein biomarkers for *Candida albicans* extracellular vesicles**"
author: "*Charlotte Dawson^a^, Mark Bleackley^a^, Marilyn Anderson^a^*"
date: "*^a^Department of Biochemistry and Genetics, La Trobe University, Victoria, Australia*"
output: 
    html_notebook: default
    bookdown::word_document2:
      pandoc_args:
        '--lua-filter=templates/pagebreak.lua'
      reference_docx: "templates/draft_template.docx"
      fig_caption: yes
    bookdown::pdf_document2:
      latex_engine: xelatex
      fig_caption: yes
      number_sections: yes
      toc: no
      keep_tex: no
bibliography: references.bib
csl: "templates/molecular-and-cellular-proteomics.csl"
link-citations: yes
linkcolor: blue
fontsize: 12pt
geometry: margin=1in
classoption: letterpaper
mainfont: Times New Roman
linestretch: 1.5
header-includes:
  - \usepackage{titling}
  - \pretitle{\begin{center}\fontsize{14bp}{14bp}\selectfont}
  - \posttitle{\par\end{center}}
  - \preauthor{\begin{center}\fontsize{12bp}{12bp}\selectfont}
  - \postauthor{\par\end{center}}
  - \predate{\begin{center}\fontsize{10bp}{10bp}\selectfont}
  - \postdate{\par\end{center}}
  - \usepackage{fancyhdr}
  - \usepackage{lipsum}
  - \pagestyle{fancy}
  - \fancyhead[L]{This is the running title it is rather long}
---

**Running title:** Running title goes here

**Corresponding author:**

\newpage

<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/"
)

library(candidaev) # Or use devtools::load_all('.', quiet = T) if your code is in script files, rather than as functions in the `/R` diretory
```

# Abbreviations

EV - extracellular vesicle

\newpage

# Abstract

The abstract goes here. Here is a citation [@liao2012].

Here is another citation [@gil-bona2018].

And another [@lin2014].

\newpage

# Introduction

Here is a citation [@marwick2017].

# Background

```{r demo, eval = FALSE}
1 + 1
```

# Methods

# Results

```{r get-data, eval = FALSE}
# Note the path that we need to use to access our data files when rendering this document
my_data <- readr::read_csv(here::here('analysis')
```

# Discussion

# Conclusion

# Acknowledgements

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

