---
title: "Analysis"
author: "Charlotte Dawson"
date: "2018-01-20"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    df_print: kable
vignette: > 
  %\VignetteIndexEntry{Vignette title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(collapse = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      echo = FALSE,
                      comment = "#>")
# use fig.path="../vignettes/figures" to save generated figures
library(limma)
library(dplyr)
library(ggplot2)
library(candidaev)
library(ggpubr)
library(UpSetR)

set.seed(1)
```

# Introduction


# Biofilm DAY286

## Analysis

Text.

```{r biofilmInit}
biofilm <- biofilm %>% 
  filter(Reverse != "+", Potential.contaminant != "+", 
         Only.identified.by.site != "+", Unique.peptides >= 2)

biofilm_lfq <- convert_lfq(biofilm, biofilm_exp)

b1a <- plot_frequency2(biofilm_lfq)

b1b <- plot_numbers2(biofilm_lfq, biofilm_exp) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggarrange(b1a, b1b, 
          labels = c("A", "B"), 
          ncol = 2, 
          nrow = 1, 
          font.label = list(size = 24, color = "black"))

knitr::kable(summarise_lfq(biofilm_lfq), 
             caption = "A table caption", 
             col.names = c("Sample", "Mean LFQ intensity", "Median LFQ intensity", 
                           "SD", "CV", "Min LFQ intensity", "Max LFQ intensity", 
                           "Range", "Number of proteins", "Number of NA", "Percent NA"), 
             digits = 1)

```

Text.

Text.

```{r, biofilmFilt}
# filter for proteins identified in min 4/5 reps of EV or WCL
biofilm_filt <- filter_na2(biofilm_lfq, logic = "or", op = "<=", 
                           pat1 = "EV", val1 = 1, 
                           pat2 = "W", val2 = 1)

b2a <- plot_frequency2(biofilm_filt)

b2b <- plot_numbers2(biofilm_filt, biofilm_exp) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

b2c <- plot_mds(biofilm_filt)

ggarrange(ggarrange(b2a, b2b, labels = c("A", "B"), ncol = 1, nrow = 2, 
                    font.label = list(size = 24, color = "black")), 
          b2c, 
          labels = c("", "C"), 
          ncol = 2, 
          nrow = 1, 
          font.label = list(size = 24, color = "black"))
```

Text.

```{r, biofilmNorm}
biofilm_norm <- normalizeCyclicLoess(biofilm_filt)

b3a <- plot_normalization2(biofilm_exp, biofilm_filt, biofilm_norm)

b3b <- plot_mds(biofilm_norm)

b3c <- plot_dendro(biofilm_norm)

ggarrange(b3a, 
          ggarrange(b3b, b3c, labels = c("B", "C"), ncol = 1, nrow = 2, font.label = list(size = 24, color = "black")), 
          labels = c("A", ""), 
          ncol = 2, 
          nrow = 1, 
          font.label = list(size = 24, color = "black"))

```

Text.


```{r biofilmVenn}
# filter for proteins identified in min 1/5 reps of EV
b_ev <- filter_na(biofilm_norm, op = "<=", 
                  pat = "EV", val = 4)

# filter for proteins identified in min 1/5 reps of WCL
b_wcl <- filter_na(biofilm_norm, op = "<=", 
                   pat = "W", val = 4)

b4 <- plot_venn(list("EV" = b_ev, "WCL" = b_wcl), 
                 use_uniprot = TRUE, type = "plot")

b4 <- as_ggplot(b4) + 
  theme(plot.margin = unit(c(0,2,0,2), "lines"))

plot(b4)

```

Text

```{r biofilmTop10}
# get top 10 most abundant protein exclusive to biofilm EVs
# in descending order of abundance
biofilm_top10 <- b_ev %>% 
  tibble::as_tibble(rownames = "id") %>% 
  filter_na(., op = "==", pat = "W", val = 5) %>% 
  select(-contains("W")) %>% 
  mutate(mean = rowMeans(select(., contains("EV")), na.rm = TRUE)) %>% 
  top_n(n = 10, wt = mean) %>% 
  arrange(desc(mean)) %>% 
  mutate(protein_name = match_id(id, uniprot, "UP_accession", "CGD_gene_name"), 
         GO_CC = match_id(id, uniprot, "UP_accession", "GO_CC"))

knitr::kable(biofilm_top10, 
             caption = "This is a table caption", 
             digits = 1)
  

```

Text.

```{r biofilmSum}
# explore percentage missing values in each sample
knitr::kable(summarise_lfq(biofilm_norm), 
             caption = "A table caption", 
             col.names = c("Sample", "Mean LFQ intensity", "Median LFQ intensity", 
                           "SD", "CV", "Min LFQ intensity", "Max LFQ intensity", 
                           "Range", "Number of proteins", "Number of NA", "Percent NA"), 
             digits = 1)

```

TEXT.

TEXT.

```{r biofilmSum2, cache=TRUE}
# should not impute with so many missing values
# filter for proteins with 4-5 NA values in EV or WCL
biofilm_excl <- filter_na2(biofilm_norm, logic = "or", op = ">=", 
                         pat1 = "EV", val1 = 4, 
                         pat2 = "W", val2 = 4)

# filter for proteins with min 3 valid values in EV and WCL
biofilm_both <- filter_na2(biofilm_norm, logic = "and", op = "<=", 
                         pat1 = "EV", val1 = 3, 
                         pat2 = "W", val2 = 3)

knitr::kable(summarise_lfq(biofilm_both), 
             caption = "A table caption", 
             col.names = c("Sample", "Mean LFQ intensity", "Median LFQ intensity", 
                           "SD", "CV", "Min LFQ intensity", "Max LFQ intensity", 
                           "Range", "Number of proteins", "Number of NA", "Percent NA"), 
             digits = 1)

b5a <- grid::grid.grabExpr(plot_missval2(biofilm_both))

b5b <- grid::grid.grabExpr(plot_detect2(biofilm_both))

ggarrange(b5a, b5b, 
          labels = c("A", "B"), 
          ncol = 2, 
          nrow = 1, 
          font.label = list(size = 24, colour = "black"))

```

TEXT. 

```{r biofilmImpute}
# proteins with missing values tend to have lower intensity
# therefore proteins are MNAR, close to detection limit

# use left censored imputation method
biofilm_imp <- impute_QRILC(biofilm_both)

plot_imputation2(biofilm_exp, biofilm_both, biofilm_imp)

```

TEXT.

```{r biofilmDE}
# recombine imputed proteins and non-imputed proteins in matrix
biofilm_de <- rbind(biofilm_excl, biofilm_imp)

# see limma user guide section 9.2 for more info about DE
# create design matrix
b_samp <- data.frame(T = (rep(c("EV", "WCL"), each = 5)))
b_design <- stats::model.matrix(~ 0 + T, data = b_samp)
colnames(b_design) <- c("EV", "WCL")

# make all pair-wise comparisons between EV and WCL
b_cm <- makeContrasts("EV_vs_WCL" = EV - WCL, levels = b_design)
b_fit <- lmFit(biofilm_de, design = b_design)
b_fit_cm <- contrasts.fit(b_fit, b_cm)
b_efit <- eBayes(b_fit_cm)

# extract DE results and create results table
biofilm_tt <- topTable(b_efit, sort.by = "none", number = Inf) %>% 
  as.matrix()

biofilm_res <- combine_result(mat = biofilm_de, toptab = biofilm_tt) %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column(var = "UP_accession") %>% 
  mutate(group = case_when(significant == 0 ~ "not sig",
                           significant == 1 & logFC > 0 ~ "ev up",
                           significant == 1 & logFC < 0 ~ "wcl up",
                           is.na(significant) == TRUE & UP_accession %in% rownames(b_ev) ~ "ev ex",
                           is.na(significant) == TRUE & UP_accession %in% rownames(b_wcl) ~ "wcl ex"),
         in_ev = ifelse(UP_accession %in% rownames(b_ev), TRUE, FALSE),
         in_wcl = ifelse(UP_accession %in% rownames(b_wcl), TRUE, FALSE),
         CGD_gene_name = match_id(.[["UP_accession"]], uniprot, "UP_accession", "CGD_gene_name"),
         Protein_name = match_id(.[["UP_accession"]], uniprot, "UP_accession", "Protein_name"), 
         significant = as.logical(significant)) %>%
  select(UP_accession, CGD_gene_name, Protein_name, everything())

biofilm_res_short <- biofilm_res %>% 
  select(CGD_gene_name, Protein_name, logFC, AveExpr, adj.P.Val, significant, group) %>% 
  mutate_at(.vars = vars(logFC, AveExpr), 
            .funs = list(~round(., digits = 2))) %>% 
  mutate(adj.P.Val = signif(adj.P.Val, digits = 3), 
         group = as.factor(group))

DT::datatable(biofilm_res_short, 
              caption = "This is a table caption. Note that adjusted p values have been shortened
              to three significant figures for ease of display.", 
              rownames = FALSE, 
              colnames = c("Gene" = "CGD_gene_name", 
                           "Protein" = "Protein_name", 
                           "p.adj" = "adj.P.Val", 
                           "sig" = "significant"), 
              filter = list(position = "bottom", clear = FALSE, plain = TRUE), 
              class = "display compact", 
              options = list(
                autowidth = TRUE, 
                columnDefs = list(list(width = "40%", targets = 1), 
                                  list(width = "10%", targets = c(0, 2:6)), 
                                  list(targets = 1, 
                                       render = DT::JS(
                                         "function(data, type, row, meta) {",
                                         "return type === 'display' && data.length > 40 ?",
                                         "'<span title=\"' + data + '\">' + data.substr(0, 40) + '...</span>' : data;",
                                         "}")), 
                                  list(targets = 0, 
                                       render = DT::JS("function(data, type, row, meta) {",
                                         "return type === 'display' && data.length > 12 ?",
                                         "'<span title=\"' + data + '\">' + data.substr(0, 12) + '...</span>' : data;",
                                         "}"))
                                  )
                )
              )


```


# Comparison to previous data

TEXT

```{r biofilmComp}
z_list_b <- zarnowski %>% 
  filter(Biofilm_NTS > 0) %>% 
  mutate(gn = match_id(UP_accession, uniprot, "UP_accession", "CGD_gene_name")) %>% 
  pull(gn)

b_ev_list <- match_id(rownames(b_ev), uniprot, "UP_accession", "CGD_gene_name", concat = FALSE)

c1 <- plot_venn(list("mylist" = b_ev_list, "Zarn" = z_list_b), 
                 use_uniprot = FALSE, type = "plot")

c1 <- as_ggplot(c1) + 
  theme(plot.margin = unit(c(0,2,0,2), "lines"))

plot(c1)

```

TEXT















