# Function descriptions for Table 1 and Table S2


## @knitr fun_list1
function_desc1 <- c("1,3-beta-glucanosyltransferase",
                    "Rho family GTPase",
                    "Multidrug transporter of ABC superfamily",
                    "Major chitin synthase of yeast and hyphae",
                    "GPI-anchored cell wall transglycosylase",
                    "GPI-anchored cell wall protein",
                    paste0("Predicted P-type ATPase sodium pump",
                           footnote_marker_alphabet(1)),
                    "ER oxidoreductin",
                    "Multicopper feroxidase",
                    "High-affinity S-adenosylmethionine permease",
                    "1,3-beta-glucan synthase",
                    "High-affinity MFS glucose transporter",
                    "Putative high-affinity MFS glucose transporter",
                    "Putative MFS glucose transporter",
                    paste0("Putative mitochondrial phosphate transporter",
                           footnote_marker_alphabet(1)),
                    "Cell surface mannoprotein",
                    "Mucin family adhesin-like protein",
                    "Sphingolipid C9-methyltransferase",
                    paste0("\\textit{S. cerevisiae} ortholog is Pom33, transmembrane nucleoporin",
                           footnote_marker_alphabet(2)),
                    paste0("\\textit{S. cerevisiae} ortholog is Yop1, reticulon-interacting protein",
                           footnote_marker_alphabet(2)),
                    paste0("\\textit{S. cerevisiae} ortholog is Rtn1, reticulon protein",
                           footnote_marker_alphabet(2)),
                    paste0("\\textit{S. cerevisiae} ortholog is Pun1, plasma membrane protein",
                           footnote_marker_alphabet(2)),
                    "1,3-beta-glucanosyltransferase",
                    "GPI-anchored cell surface protein of unknown function",
                    "Putative ion transporter",
                    "Cell surface glycosidase",
                    "Glycosidase",
                    "Phospholipase B",
                    "Plasma membrane ATPase",
                    paste0("Mitochondrial outer membrane porin",
                           footnote_marker_alphabet(1)),
                    "G-protein of RAC subfamily",
                    "Rho family GTPase",
                    "Rho family GTPase",
                    "Secreted aspartyl protease",
                    paste0("Protein required for normal cell wall, plasma membrane",
                           footnote_marker_alphabet(3)),
                    paste0("Protein involved in vacuolar inheritance",
                           footnote_marker_alphabet(1)),
                    "\\textit{S. cerevisiae} ortholog is Yck2, casein kinase",
                    paste0("Palmitoyltransferase, putative vacuolar SNARE complex protein",
                           footnote_marker_alphabet(1)),
                    "Secreted yeast cell wall protein")

## @knitr fun_list2
function_desc2 <- c(paste0("Putative alpha-mannosidase",
                           footnote_marker_alphabet(1)),
                    "Vacuolar aspartic proteinase",
                    paste0("Thioredoxin peroxidase",
                           footnote_marker_alphabet(1)),
                    paste0("Putative 2-enoyl thioester reductase",
                           footnote_marker_alphabet(1)),
                    paste0("Glycine decarboxylase P subunit",
                           footnote_marker_alphabet(1)),
                    "Glycerol 2-dehydrogenase",
                    paste0("Putative glycogen debranching enzyme",
                           footnote_marker_alphabet(2)),
                    paste0("Glutathione reductase",
                           footnote_marker_alphabet(1)),
                    "Glutathione-independent glyoxalase",
                    "Phosphoglycerate mutase",
                    paste0("Aspartate-semialdehyde dehydrogenase",
                           footnote_marker_alphabet(2)),
                    paste0("Heat shock protein 60",
                           footnote_marker_alphabet(1)),
                    paste0("Isocitrate dehydrogenase subunit",
                           footnote_marker_alphabet(1)),
                    paste0("Isocitrate dehydrogenase",
                           footnote_marker_alphabet(1)),
                    "Dihydrolipoamide dehydrogenase",
                    "O-acetylhomoserine O-acetylserine sulfhydrylase",
                    paste0("Non-histone chromosomal protein 6",
                           footnote_marker_alphabet(1)),
                    paste0("\\textit{S. cerevisiae} ortholog is Nif3, mitochondrial protein",
                           footnote_marker_alphabet(1)),
                    paste0("\\textit{S. cerevisiae} ortholog is Lpx1, peroxisomal lipase",
                           footnote_marker_alphabet(2)),
                    paste0("Protein of unknown function",
                           footnote_marker_alphabet(3)),
                    paste0("Predicted dienelactone hydrolase domain",
                           footnote_marker_alphabet(2)),
                    paste0("20S proteasome subunit (beta7)",
                           footnote_marker_alphabet(1)),
                    paste0("Putative phosphatidyl synthase",
                           footnote_marker_alphabet(2)),
                    paste0("Stationary phase enriched protein",
                           footnote_marker_alphabet(2)),
                    "Putative thiamine biosynthesis enzyme",
                    paste0("\\textit{S. cerevisiae} ortholog is Stm1, regulates translation",
                           footnote_marker_alphabet(1)),
                    paste0("Putative esterase", footnote_marker_alphabet(1)),
                    paste0("\\textit{S. cerevisiae} ortholog is Hsp10, mitochondrial co-chaperonin",
                           footnote_marker_alphabet(1)),
                    paste0("Putative X-Pro aminopeptidase",
                           footnote_marker_alphabet(2)),
                    paste0("NADPH oxidoreductase family protein",
                           footnote_marker_alphabet(2)),
                    paste0("Glucose-6-phosphate isomerase",
                           footnote_marker_alphabet(2)),
                    paste0("\\textit{S. cerevisiae} ortholog is Sbp1, eIF4G binding protein",
                           footnote_marker_alphabet(1)),
                    paste0("Proteasome subunit YC7alpha",
                           footnote_marker_alphabet(1)),
                    "Superoxide dismutase",
                    paste0("HSP90 co-chaperone",
                           footnote_marker_alphabet(1)),
                    paste0("Translation initiation factor eIF1a",
                           footnote_marker_alphabet(1)),
                    paste0("\\textit{S. cerevisiae} ortholog is Tma19, ribosome associated protein",
                           footnote_marker_alphabet(1)),
                    paste0("Predicted succinate semialdehyde dehydrogenase",
                           footnote_marker_alphabet(1)),
                    paste0("Putative xylulokinase", footnote_marker_alphabet(2)),
                    "Nucleoside disphosphate kinase")
