#' Visualize intensities of proteins with missing values
#'
#' \code{plot_detect} generates density and CumSum plots
#' of protein intensities with and without missing values
#'
#' @param se SummarizedExperiment,
#' Data object with missing values.
#' @return Density and CumSum plots of intensities of
#' proteins with and without missing values
#' (generated by \code{\link[ggplot2]{ggplot}}).
#' @examples
#' # Load example
#' data <- UbiLength
#' data <- data[data$Reverse != "+" & data$Potential.contaminant != "+",]
#' data_unique <- make_unique(data, "Gene.names", "Protein.IDs", delim = ";")
#'
#' # Make SummarizedExperiment
#' columns <- grep("LFQ.", colnames(data_unique))
#' exp_design <- UbiLength_ExpDesign
#' se <- make_se(data_unique, columns, exp_design)
#'
#' # Filter
#' filt <- filter_missval(se, thr = 0)
#'
#' # Plot intensities of proteins with missing values
#' plot_detect(filt)
#' @export
plot_detect2 <- function(lfq_mat) {
  # Show error if inputs are not the required classes
  assertthat::assert_that(is.matrix(lfq_mat))

  # Show error if there are no missing values
  if(!any(is.na(lfq_mat))) {
    stop("No missing values in '", deparse(substitute(lfq_mat)), "'",
         call. = FALSE)
  }

  # Get a long data.frame of the assay data annotated with sample info
  df <- lfq_mat %>%
    data.frame() %>%
    rownames_to_column() %>%
    gather(ID, val, -rowname)

  # Get a summarized table with mean protein intensities and
  # indication whether the protein has missing values
  stat <- df %>%
    group_by(rowname) %>%
    summarize(mean = mean(val, na.rm = TRUE), missval = any(is.na(val)))

  # Calculate cumulative fraction
  cumsum <- stat %>%
    group_by(missval) %>%
    arrange(mean) %>%
    mutate(num = 1, cs = cumsum(num), cs_frac = cs/n())

  # Plot the densities and cumalitive fractions for
  # proteins with and without missing values
  p1 <- ggplot(stat, aes(mean, col = missval)) +
    geom_density(na.rm = TRUE) +
    labs(x = expression(log[2]~"Intensity"), y = "Density") +
    guides(col = guide_legend(title = "Missing values")) +
    theme_bw()
  p2 <- ggplot(cumsum, aes(mean, cs_frac, col = missval)) +
    geom_line() +
    labs(x = expression(log[2]~"Intensity"), y = "Cumulative fraction") +
    guides(col = guide_legend(title = "Missing values")) +
    theme_bw()
  gridExtra::grid.arrange(p1, p2, ncol = 1)
}
