#' Plot frequency of protein quantification between samples
#'
#' @description \code{plot_frequency2} generates a bar plot of how many proteins are
#' quantified in only 1 out of x samples, 2 out of x samples, 3 out of
#' x samples, etc., i.e. protein quantification frequency.
#'
#' This function has been taken directly from the \code{plot_frequency} function
#' in the \href{http://doi.org/10.18129/B9.bioc.DEP}{DEP} package and then
#' modified for use in this package.
#'
#' \href{http://doi.org/10.18129/B9.bioc.DEP}{DEP} is distributed with the Artistic-2.0 license
#' which requires any source code modifications to be clearly stated.
#'
#' \code{plot_frequency2} includes the following modifications of \code{plot_frequency}:
#'
#' \itemize{
#' \item Dependance on a "SummarizedExperiment" object as input has been removed.
#' Instead the input has been changed to a numeric matrix.
#' \item Use of \code{theme_DEP1()} has been replaced with \code{theme_bw()}
#' \item Plot title has been changed to "Protein quantification frequency".
#' }
#'
#' @param mat numeric matrix: protein log2 LFQ intensity data
#'
#' @param plot logical:
#' if \code{TRUE} (default) the barplot is produced.
#' Otherwise if \code{FALSE}, the data on which the
#' barplot is based are returned
#'
#' @return Returns a bar plot of the frequency of protein quantification
#' between samples
#' (generated by \code{\link[ggplot2]{ggplot}}). If \code{plot = FALSE},
#' returns a \code{data.frame} with the data underlying the bar plot.
#'
#' @examples
#' # load dplyr
#' library(dplyr)
#'
#' # load a proteinGroups data.frame supplied with this package
#' my_proteinGroups <- atcc
#'
#' # load its corresponding experimental design
#' my_expDesign <- atcc_exp
#'
#' # filter for proteins identified with minimum 3 unique peptides
#' # and convert to numeric matrix
#' my_lfq <- my_proteinGroups %>%
#'   filter(Unique.peptides >= 3) %>%
#'   convert_lfq(., my_expDesign)
#'
#' # generate bar plot of protein quantification frequency
#' plot_frequency2(my_lfq)
#'
#' @import ggplot2
#'
#' @export
plot_frequency2 <- function(mat, plot = TRUE) {
  # Show error if input is not the required classes
  assertthat::assert_that(is.matrix(mat),
                          is.logical(plot),
                          length(plot) == 1)

  # Make a binary long data.frame (1 = valid value, 0 = missing value)
  df <- mat %>%
    data.frame() %>%
    tibble::rownames_to_column() %>%
    tidyr::gather(ID, bin, -rowname) %>%
    mutate(bin = ifelse(is.na(bin), 0, 1))
  # Identify the number of experiments a protein was observed
  stat <- df %>%
    group_by(rowname) %>%
    summarise(sum = sum(bin))
  # Get the frequency of the number of experiments proteins
  # were observerd and plot these numbers
  table <- table(stat$sum) %>% data.frame()
  p <- ggplot(table, aes(x = Var1, y = Freq, fill = Var1)) +
    geom_col() +
    scale_fill_grey(start = 0.8, end = 0.2) +
    labs(title = "Protein quantification frequency",
         x = "Quantified in number of samples",
         y = "Number of proteins") +
    theme_bw(base_size = 16) +
    theme(legend.position="none")
  if(plot) {
    return(p)
  } else {
    df <- as.data.frame(table)
    colnames(df) <- c("samples", "proteins")
    return(df)
  }
}
