#' Plot a heatmap of proteins with missing values
#'
#' \code{plot_missval} generates a heatmap of proteins
#' with missing values to discover whether values are missing by random or not.
#'
#' @param mat SummarizedExperiment,
#' Data object with missing values.
#' @return A heatmap indicating whether values are missing (0) or not (1)
#' (generated by \code{\link[ComplexHeatmap]{Heatmap}}).
#' @examples
#' \dontrun{
#' # Load example
#' data <- UbiLength
#' data <- data[data$Reverse != "+" & data$Potential.contaminant != "+",]
#' data_unique <- make_unique(data, "Gene.names", "Protein.IDs", delim = ";")
#'
#' # Make SummarizedExperiment
#' columns <- grep("LFQ.", colnames(data_unique))
#' exp_design <- UbiLength_ExpDesign
#' se <- make_se(data_unique, columns, exp_design)
#'
#' # Filter, normalize and impute missing values
#' filt <- filter_missval(se, thr = 0)
#'
#' # Plot missing values heatmap
#' plot_missval(filt)
#' }
#' @export
plot_missval2 <- function(mat) {
  # Show error if input is not the required classes
  assertthat::assert_that(is.matrix(mat))

  # Show error if there are no missing values
  if(!any(is.na(mat))) {
    stop("No missing values in '", deparse(substitute(mat)), "'",
         call. = FALSE)
  }

  # Make assay data binary (1 = valid value, 0 = missing value)
  df <- mat %>%
    data.frame()
  missval <- df[apply(df, 1, function(x) any(is.na(x))), ]
  missval <- ifelse(is.na(missval), 0, 1)
  # Plot binary heatmap
  ht2 = ComplexHeatmap::Heatmap(missval,
                                col = c("white", "black"),
                                column_names_side = "top",
                                show_row_names = FALSE,
                                show_column_names = TRUE,
                                name = "Missing values pattern",
                                column_names_gp = gpar(fontsize = 16),
                                heatmap_legend_param = list(at = c(0, 1),
                                                            labels = c("Missing value", "Valid value")))
  ComplexHeatmap::draw(ht2, heatmap_legend_side = "top")
}
