#' Visualise GO term coverage
#'
#' @description \code{plot_go_bar} generates a bar plot of specific GO terms from
#' the output of \code{\link{process_fungifun}}.
#'
#' The length of the bars indicates the percentage of the all the GO term proteins
#' that are present in the protein list used to query FungiFun2. The colour of the
#' bars indicates the specific GO domain a GO term is under: biological process
#' (BP), cellular component (CC), molecular function (MF).
#'
#' @param go_table data.frame: output of \code{\link{process_fungifun}}
#'
#' @param terms_list numeric vector: row numbers of the GO terms to be plotted
#'
#' @param col_pal character vector (length = 3): names of three colours to use
#' for indicating BP, CC, MF.
#'
#' @return Returns a bar plot of the specified GO terms (generated by
#' \code{\link[ggplot2]{ggplot}}).
#'
#' @examples
#' \donttest{
#' # import a FungiFun2 output .csv file
#' go_table <- process_fungifun("./vignettes/figures/f4_GO_DAY_Y.csv")
#'
#' # define a colour palette
#' go_pal <- c("#6D2077", "#E4002B", "#FFB81C")
#'
#' # generate a GO term bar plot
#' plot_go_bar(go_table = go_table,
#'             terms_list = c(1:4, 10),
#'             col_pal = go_pal) +
#'  annotate("text", x = 1, y = 50, label = "bold('DAY286 Y')", parse = TRUE) +
#'  labs(fill = "GO domain") +
#'  theme(legend.text = element_text(size = 10),
#'        legend.title = element_text(size = 10))
#' }
#'
#' @export
plot_go_bar <- function(go_table, terms_list, col_pal) {
  df <- go_table[terms_list, ]

  df <- df %>%
    arrange(adj.p.val)

  ggplot(data = df,
         aes(x = stats::reorder(GO.term, rev(adj.p.val)),
             y = Cat.ratio*100)) +
    geom_bar(stat = "identity", aes(fill = GO.type)) +
    theme_classic(base_size = 8) +
    scale_y_continuous(limits = c(0,100), expand = expand_scale(mult = c(0, .05))) +
    labs(x = NULL,
         y = "Percent GO term coverage",
         fill = "GO category") +
    theme(legend.justification = c(1,0),
          legend.position = "top",
          axis.text.x = element_text(size = 8),
          axis.text.y = element_text(size = 7, colour = "black"),
          panel.grid.major.x = element_line(size = 0.2, colour = "black")) +
    scale_fill_manual(values = col_pal) +
    coord_flip()
}
