#' Plot a heatmap of proteins with missing values
#'
#' @description \code{plot_missval2} generates a heatmap of proteins
#' with missing values to observe the pattern of missing values across the
#' samples (random or not random).
#'
#' This function has been taken directly from the \code{plot_missval}
#' function in the \href{http://doi.org/10.18129/B9.bioc.DEP}{DEP} package and
#' then modified for use in this package.
#'
#' \href{http://doi.org/10.18129/B9.bioc.DEP}{DEP} is distributed with the
#' Artistic-2.0 license
#' which requires any source code modifications to be clearly stated.
#'
#' \code{plot_missval2} includes the following modifications
#' of \code{plot_missval}:
#'
#' \itemize{
#' \item Dependance on a "SummarizedExperiment" object as input has been
#' removed. Instead the input has been changed to a numeric matrix.
#' }
#'
#' @param mat numeric matrix: must have missing values
#'
#' @return Returns a heatmap indicating whether values are missing (white) or
#' not (black)
#' (generated by \code{\link[ComplexHeatmap]{Heatmap}}).
#'
#' @examples
#' # load dplyr
#' library(dplyr)
#'
#' # load a proteinGroups data.frame supplied with this package
#' my_proteinGroups <- atcc
#'
#' # load its corresponding experimental design
#' my_expDesign <- atcc_exp
#'
#' # filter for proteins identified with minimum 3 unique peptides
#' # and convert to numeric matrix
#' my_lfq <- my_proteinGroups %>%
#'   filter(Unique.peptides >= 3) %>%
#'   convert_lfq(., my_expDesign)
#'
#' # filter for proteins quantified in min 2/3 reps of
#' # at least 1 sample group
#' my_filt <- my_lfq %>%
#'   filter_na4(., logic = "or", op = "<=",
#'              pat1 = "A10231_EV", val1 = 1,
#'              pat2 = "A10231_W", val2 = 1,
#'              pat3 = "A90028_EV", val3 = 1,
#'              pat4 = "A90028_W", val4 = 1)
#'
#' # plot missing value heatmap
#' plot_missval2(my_filt)
#'
#' @export
plot_missval2 <- function(mat) {
  # Show error if input is not the required classes
  assertthat::assert_that(is.matrix(mat))

  # Show error if there are no missing values
  if(!any(is.na(mat))) {
    stop("No missing values in '", deparse(substitute(mat)), "'",
         call. = FALSE)
  }

  # Make assay data binary (1 = valid value, 0 = missing value)
  df <- mat %>%
    as.data.frame()
  missval <- df[apply(df, 1, function(x) any(is.na(x))), ]
  missval <- ifelse(is.na(missval), 0, 1)

  # Define heatmap legend parameters
  legend_param <- list(at = c(0, 1),
                       labels = c("Missing value",
                                  "Valid value"))

  # Plot binary heatmap
  ht2 = ComplexHeatmap::Heatmap(missval,
                                col = c("white", "black"),
                                column_names_side = "top",
                                show_row_names = FALSE,
                                show_column_names = TRUE,
                                name = "Missing values pattern",
                                column_names_gp = grid::gpar(fontsize = 16),
                                heatmap_legend_param = legend_param)
  ComplexHeatmap::draw(ht2, heatmap_legend_side = "top")
}
